### ISSUE TITLE
Создать имитацию отправки реального пакета на сервер Глонас 

### ISSUE THREAD

**Issue by zzzkorn** [zzzkorn/progress-proxylogger#7]
ip адрес реального сервера: 193.232.47.4
port реального сервера: 40005

30 01 00 03 0B 00 23 00 0A 00 01 9C 18 00 0A 00 9C 00 C5 C2 B4 02 02 10 15 00 00 C5 C2 B4 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00 23 3E 4B

**Comment by SergeAbramyan** [comment]
[autorization.txt](https://github.com/zzzkorn/progress-proxylogger/files/10295093/autorization.txt)
[autorization1.txt](https://github.com/zzzkorn/progress-proxylogger/files/10295094/autorization1.txt)
[send.txt](https://github.com/zzzkorn/progress-proxylogger/files/10295095/send.txt)

**Comment by zzzkorn** [comment]
[drozdov.pcapng.zip](https://github.com/zzzkorn/progress-proxylogger/files/10411673/drozdov.pcapng.zip)
